name: kermut_env_update
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - python=3.12
  - pytorch
  - pytorch-cuda=11.8
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - h5py
  - biopython
  - tqdm
  - pip:
    - fair-esm
    - gpytorch
    - hydra-core